### PR TITLE
Cleaning up the GUI for Ease of Access and Modification

### PR DESCRIPTION
**Pull request by AaronWB**
Split the main GUI class into 9 other classes for easy way to change each portion of the code.

Put each section of code into their own package for (CLI, GUI, Backend).

Detailed JavaDocs for each method so our new team member can understand them.

### CODE REVIEW

**Review by colbycrutcher — COMMENTED** [review]
No questions about code. Overall stayed the same for the most part, but split into classes for managing code. We had 600 some lines of code in the gui before. overall this will help readability and changes

**Comment by SergeiAshikhmin** [comment]
I think this looks good. Excellent work splitting GraphicalInterface into smaller classes. Now, the project's structure looks much better, especially for me as a new team member; it makes navigating specific features and their implementations easier.

**Review by colbycrutcher — APPROVED** [review]
Just approving

**Review by SergeiAshikhmin — APPROVED** [review]
Also approving.

**Pull request merged**
